name: Build rockchip 6.12 firmware
on: [push]

jobs:
    build:
        name: Build rockchip linux v6.12 images
        runs-on: ubuntu-24.04-arm

        steps:
            - name: Setup Ubuntu
              run: |
                sudo apt update
                sudo apt install -y subversion build-essential gettext 2to3 python3-pyelftools python3-distutils-extra
            - name: Setup Go
              uses: actions/setup-go@main
              with:
                go-version: '1.25.4'
            - name: Checkout
              uses: actions/checkout@main

            - name: Build
              run: |
                git clone https://github.com/mj22226/openwrt.git
                cd openwrt
                git pull
                git checkout linux-6.6
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/363cefecd314e45b49d8eafff8473fcf/raw/f327d1fcae5513be3abbeea1c6696c1da845a635/01-diskman.patch
                wget https://github.com/mj22226/luci/commit/8f4a290b4e8ecd64888ad1feea9c2b3c6383cc60.patch
                wget https://github.com/mj22226/luci/commit/22c05f0beb664c8d4cbc0a9b6fa17a5feb00f5bb.patch
                git apply 01-diskman.patch
                git apply 8f4a290b4e8ecd64888ad1feea9c2b3c6383cc60.patch
                git apply 22c05f0beb664c8d4cbc0a9b6fa17a5feb00f5bb.patch
                wget https://github.com/mj22226/luci/commit/239fd8e34a7e3d85d104be72b385ce46ccb9dfb4.patch
                rm -rf applications/luci-app-dockerman
                git apply 239fd8e34a7e3d85d104be72b385ce46ccb9dfb4.patch
                cd -
                cd  feeds/packages
                rm -rf net/openvpn
                wget https://github.com/mj22226/packages/commit/edb8a63a5a69a13848aa39d9298ebb39972daf41.patch
                git apply edb8a63a5a69a13848aa39d9298ebb39972daf41.patch
                wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/2cf67633587d351b66fdf1bd902df6494cd42e68/01-cpu.patch
                wget https://gist.githubusercontent.com/mj22226/b66f5c1bd5fc7e1cb3cf2c690b5dbd5a/raw/b955e726cbb0948d932c8d6143229ad604320149/20-lxc.patch
                git apply 01-cpu.patch
                git apply 20-lxc.patch
                cd -
                sed -i "71s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "84s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "195s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "212s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                sed -i "4s/login/login -f root/" feeds/packages/utils/ttyd/files/ttyd.config
                sed -i '12d' feeds/luci/applications/luci-app-attendedsysupgrade/Makefile
                echo "# CONFIG_DRM_WERROR is not set" >> target/linux/generic/config-6.12
                rm -f target/linux/generic/hack-6.12/930-Revert-Revert-Revert-driver-core-Set-fw_devlink-on-b.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                wget https://github.com/mj22226/openwrt-arm64/releases/download/rockchip-22.1.3/llvm-bpf-22.1.3.Linux-aarch64.tar.zst
                tar -xvf llvm-bpf-22.1.3.Linux-aarch64.tar.zst
                cp .github/workflows/rk-config .config
                echo 'CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT="/opt/hostedtoolcache/go/1.25.4/arm64/bin"' >> .config
                make defconfig
                wget https://gist.githubusercontent.com/mj22226/9a69bb754a83e8a5cf03fcc60d62d473/raw/cc6f36831d6098de4a7fccf04a312d36a0dbc999/01-key.patch
                git apply 01-key.patch
                make download -j32
                rm 01-key.patch
                mkdir -p files/www/repo
                wget https://gist.githubusercontent.com/mj22226/2ce53b7a5e5742be6f9052a4e4d3203d/raw/674531914187c1afa92427ef51e6fa01f95aae3f/feeds-rk.patch
                git apply feeds-rk.patch
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/rockchip/armv8/packages
                echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
                echo "HASH=$(git log -1 --format="%H")" >> $GITHUB_ENV
            - name: Delete tag
              run: gh release delete rockchip-6.12 --cleanup-tag || true
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@main
              with:
                allowUpdates: true
                commit: ${{ env.HASH }}
                name: Rockchip v6.12 Images ${{ env.DATE }}
                tag: rockchip-6.12
                replacesArtifacts: true
                prerelease: false
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/rockchip/armv8/*
